### ISSUE TITLE
PyScipOpt references old Scip version. Problem at import of pyscipopt

### ISSUE THREAD

**Issue by windgaetter** [scipopt/PySCIPOpt#944]
**Describe the bug**
Since the last Scip update, PyScipOpt references the wrong libscip version. This results in an error when importing pyscipopt. Currently conda automatically installs Scip 9.2 and PyScipOpt 5.2.1

**To Reproduce**
Create conda environment and install pyscipopt from conda-forge. Try loading pyscipopt

**Expected behavior**
I would have expected, that the version is automatically updated or the referencing scip version fixed. 

**Screenshots**
>>> import pyscipopt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wind_lu/.conda/envs/test_env/lib/python3.12/site-packages/pyscipopt/__init__.py", line 11, in <module>
    from pyscipopt.scip      import Model
ImportError: libscip.so.9.1: cannot open shared object file: No such file or directory

**System**
 - OS: Ubuntu
 - 22.04
 - Scip 9.2
 - conda-forge

**Additional context**

**Comment by Joao-Dionisio** [comment]
Hey @windgaetter, thanks for letting us know. In the meantime, can you try `pip install pyscipopt` and see if this works?

**Comment by windgaetter** [comment]
Hi. I was wondering if there are any news when there will be a new conda-forge version of pyscipopt, that could fix this issue here ?

**Comment by Joao-Dionisio** [comment]
Hey @windgaetter, sorry for keeping you hanging. We suspect this is because we haven't released in a while. We're working on a new release, which should come out in the coming days

**Comment by Joao-Dionisio** [comment]
Hey @windgaetter! We just released. Can you please let us know if your problem was fixed?

**Comment by windgaetter** [comment]
@Joao-Dionisio Thanks for the new update. We can update to that new version, but run into the following: We run into the warning 

```UserWarning: linked SCIP 9.02 is not recommended for this version of PySCIPOpt - use version 9.2.1``` 

when loading the Model class. 

Interestingly in our conda env PyScipOpt is installed in conjuction with Scip 9.2.1. We have this issue in both our remote pipelines as well as locally. 

Also
```
import pyscipopt
m = pyscipopt.Model()
m.version()
```
outputs version 9.0.2 .

**Comment by Joao-Dionisio** [comment]
Thank you, @windgaetter, glad to hear that it's at least running now. This warning also showed up for other people (#951), maybe it's a problem with the linking we're doing. We'll look into it this week.

**Comment by Joao-Dionisio** [comment]
@windgaetter, can you check whether the current master version is working as expected?

**Comment by TheZwieback** [comment]
We have the same issue a warning when using the package from PyPI version PySCIPOpt-5.3.0
`UserWarning: linked SCIP 9.02 is not recommended for this version of PySCIPOpt - use version 9.2.1`

**Comment by Joao-Dionisio** [comment]
@TheZwieback, can you please check whether the behavior persists with the current master?

We still haven't released the version with the fix, but it shouldn't take long.

Meanwhile, if you don't mind me asking: When you say "We", are you part of a company or a research group? We're always very happy to see our software being used :)

**Comment by TheZwieback** [comment]
Hi @Joao-Dionisio 
we can wait for the fixed version, our tests are working currently so no rush. 
We are a company using several open and commercial solvers for optimization problems.

**Comment by windgaetter** [comment]
> [@windgaetter](https://github.com/windgaetter), can you check whether the current master version is working as expected?

@Joao-Dionisio Thanks for the update. Locally it seems to work now without warnings. The master branch version worked. But remotely it still links the wrong SCIP version. I guess the fixed version is not yet published to conda ?

**Comment by Joao-Dionisio** [comment]
@windgaetter, @TheZwieback  we just released today. Would you mind checking if it's working now?

**Comment by TheZwieback** [comment]
@Joao-Dionisio it is working now, thanks

**Comment by windgaetter** [comment]
@Joao-Dionisio Sorry for the late update. It is also working for us.

**Comment by cmditch** [comment]
I've deleted my .venv, recreated, and re-installed the latest version of pyscipopt yet am still seeing version 9.0.2 when running:
` python -c "import pyscipopt; print(pyscipopt.Model().version())"`

Are folks getting 9.2.1 when installing `pyscipopt==5.4.1`?

**Comment by Joao-Dionisio** [comment]
@cmditch what happens if you do `pyscipopt.Model().printVersion()`?

**Comment by Joao-Dionisio** [comment]
Yeah, I think we might just get rid of it eventually, the method we're supposed to use on the SCIP side is `SCIPprintVersion`, not `SCIPversion`.

**Comment by OldPatrick** [comment]
Hey folks just wanted to add, I have the same error :-), I am still trying to figure it out.

**Comment by Joao-Dionisio** [comment]
Hey @OldPatrick! The same error the other people originally had, or the one when you use `.version()` instead of `printVersion()`?

**Comment by OldPatrick** [comment]
@Joao-Dionisio The one from @windgaetter at february the 10th, it somehow vanished in the last days, and the solver delivered excellent results again.
